# Generated by Django 4.2.1 on 2023-05-26 18:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(regex='^[^<>/]')], verbose_name='оглавление')),
                ('content', models.TextField(max_length=500, verbose_name='описание')),
                ('status', models.BooleanField(default=False)),
                ('dateCreate', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('dateOfCompletion', models.DateField(verbose_name='Срок выполнения')),
                ('imageTask', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Фото')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['id'],
            },
        ),
    ]
